apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hubble-route
  namespace: argocd
spec:
  project: core
  source:
    repoURL: https://github.com/fwfurtado/the-lab-zone.git
    targetRevision: main
    path: apps/core/hubble-route/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
