locals {
  harbor_fqdn = "harbor.mgmt.the-lab.zone"

  # remote-exec "inline" concatena tudo num único script: set/trap/export/vars persistem.
  harbor_script = [
    "set -euo pipefail",
    "trap 'echo \"[harbor-provision] FALHOU -> $BASH_COMMAND (linha $LINENO)\" >&2' ERR",
    "exec >> /var/log/harbor-provision.log 2>&1",
    "cloud-init status --wait || true",
    "export DEBIAN_FRONTEND=noninteractive",

    # ── [1/6] Pré-requisitos + Docker ─────────────────────────────────────
    "echo '==> [1/6] apt + docker'",
    "apt-get update -qq",
    "apt-get install -y -qq ca-certificates curl",
    "curl -fsSL https://get.docker.com | sh",
    "systemctl enable --now docker",

    # ── [2/6] Disco dedicado de blobs (virtio1 -> /dev/vdb) em /data ─────
    "echo '==> [2/6] disco de dados /data'",
    "if ! blkid /dev/vdb >/dev/null 2>&1; then mkfs.ext4 -F -L harbor-data /dev/vdb; fi",
    "mkdir -p /data",
    "grep -q '/dev/vdb' /etc/fstab || echo '/dev/vdb /data ext4 defaults,discard 0 2' >> /etc/fstab",
    "mount -a",

    # ── [3/6] TLS via lego v5 (DNS-01 Cloudflare) ────────────────────────
    # v5: `run` vem ANTES das flags. Cópia do cert é robusta a layout (find por FQDN).
    "echo '==> [3/6] TLS via lego (DNS-01)'",
    "mkdir -p /etc/lego /etc/harbor/tls",
    "cat > /etc/lego/cloudflare.env <<'EOF'",
    "CF_DNS_API_TOKEN=${var.cloudflare_dns_api_token}",
    "EOF",
    "chmod 600 /etc/lego/cloudflare.env",
    "if [ ! -f /etc/lego/certificates/${local.harbor_fqdn}.crt ]; then docker run --rm --env-file /etc/lego/cloudflare.env -v /etc/lego:/etc/lego ${var.lego_image} run --accept-tos --email ${var.acme_email} --dns cloudflare --dns.resolvers ${var.acme_propagation_resolver} --domains ${local.harbor_fqdn} --path /etc/lego; fi",
    # script de deploy do cert — reusado pelo provision e pelo renew (uid 10000 do Harbor precisa LER -> 0644)
    "cat > /usr/local/bin/harbor-cert-deploy.sh <<'EOF'",
    "#!/bin/sh",
    "set -e",
    "CRT=$(find /etc/lego -type f -name '${local.harbor_fqdn}.crt' | head -1)",
    "KEY=$(find /etc/lego -type f -name '${local.harbor_fqdn}.key' | head -1)",
    "test -n \"$CRT\" && test -n \"$KEY\"",
    "install -m 0644 \"$CRT\" /etc/harbor/tls/harbor.crt",
    "install -m 0644 \"$KEY\" /etc/harbor/tls/harbor.key",
    "EOF",
    "chmod +x /usr/local/bin/harbor-cert-deploy.sh",
    "/usr/local/bin/harbor-cert-deploy.sh",

    # ── [4/6] Installer oficial do Harbor ────────────────────────────────
    "echo '==> [4/6] download + harbor.yml'",
    "curl -fsSL -o /tmp/harbor.tgz https://github.com/goharbor/harbor/releases/download/${var.harbor_version}/harbor-online-installer-${var.harbor_version}.tgz",
    "rm -rf /opt/harbor && tar xzf /tmp/harbor.tgz -C /opt",
    "cat > /opt/harbor/harbor.yml <<'EOF'",
    "hostname: ${local.harbor_fqdn}",
    "https:",
    "  port: 443",
    "  certificate: /etc/harbor/tls/harbor.crt",
    "  private_key: /etc/harbor/tls/harbor.key",
    "harbor_admin_password: ${var.harbor_admin_password}",
    "database:",
    "  password: ${var.harbor_db_password}",
    "  max_idle_conns: 100",
    "  max_open_conns: 900",
    "data_volume: /data",
    "trivy:",
    "  ignore_unfixed: false",
    "  skip_update: false",
    "  offline_scan: false",
    "jobservice:",
    "  max_job_workers: 10",
    "log:",
    "  level: info",
    "  local:",
    "    rotate_count: 50",
    "    rotate_size: 200M",
    "    location: /var/log/harbor",
    "_version: 2.15.0",
    "EOF",
    "echo '==> [5/6] install.sh --with-trivy (demora: puxa ~10 imagens)'",
    "cd /opt/harbor && ./install.sh --with-trivy",

    # ── [6/6] Renovação automática ───────────────────────────────────────
    "echo '==> [6/6] timer de renovacao'",
    "cat > /etc/systemd/system/lego-renew.service <<'EOF'",
    "[Unit]",
    "Description=Renova TLS via lego (DNS-01) e recarrega o Harbor",
    "After=docker.service",
    "Requires=docker.service",
    "[Service]",
    "Type=oneshot",
    "ExecStart=/usr/bin/docker run --rm --env-file /etc/lego/cloudflare.env -v /etc/lego:/etc/lego ${var.lego_image} renew --days 30 --accept-tos --email ${var.acme_email} --dns cloudflare --dns.resolvers ${var.acme_propagation_resolver} --domains ${local.harbor_fqdn} --path /etc/lego",
    "ExecStartPost=/usr/local/bin/harbor-cert-deploy.sh",
    "ExecStartPost=/bin/sh -c 'cd /opt/harbor && docker compose restart'",
    "EOF",
    "cat > /etc/systemd/system/lego-renew.timer <<'EOF'",
    "[Unit]",
    "Description=Checagem diaria de renovacao do cert (lego)",
    "[Timer]",
    "OnCalendar=daily",
    "RandomizedDelaySec=3600",
    "Persistent=true",
    "[Install]",
    "WantedBy=timers.target",
    "EOF",
    "systemctl daemon-reload",
    "systemctl enable --now lego-renew.timer",
    "echo '==> harbor provisionado'",
  ]
}
