apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: domains
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/fwfurtado/the-lab-zone.git
        revision: main
        directories:
          - path: apps/*
  template:
    metadata:
      name: '{{path.basename}}'        # core, observability, data, ai, security
    spec:
      project: default
      source:
        repoURL: https://github.com/fwfurtado/the-lab-zone.git
        targetRevision: main
        path: '{{path}}'
        directory:
          recurse: true
          include: '*/app.yaml'        # contrato: só app.yaml é manifest
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
