apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: core
  namespace: argocd
spec:
  description: CNI, secrets, certs, ingress — o único projeto com poder cluster-wide
  sourceRepos:
    - https://github.com/fwfurtado/the-lab-zone.git
    - https://helm.cilium.io
    - https://argoproj.github.io/argo-helm
    - https://charts.external-secrets.io
    - https://charts.jetstack.io
    - https://1password.github.io/connect-helm-charts
    - https://github.com/kubernetes-sigs/gateway-api
    - https://openebs.github.io/openebs
    - https://cloudnative-pg.github.io/charts
    - https://helm.altinity.com
    - ghcr.io/stacklok/toolhive
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
