apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: observability
  namespace: argocd
spec:
  description: Métricas, logs, alertas e traces — VictoriaMetrics stack
  sourceRepos:
    - https://github.com/fwfurtado/the-lab-zone.git
    - https://victoriametrics.github.io/helm-charts
    - https://grafana.github.io/helm-charts
    - https://open-telemetry.github.io/opentelemetry-helm-charts
  destinations:
    - namespace: observability
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRole
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRoleBinding
