apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-jobs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ai
  source:
    repoURL: https://github.com/fwfurtado/the-lab-zone.git
    targetRevision: main
    path: apps/ai/jobs/manifests
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: ai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
  ignoreDifferences:
    - group: argoproj.io
      kind: WorkflowTemplate
      name: qa-indexer
      namespace: ai
      jqPathExpressions:
        - ".spec.templates[].containerSet.archiveLogs"
    - group: argoproj.io
      kind: WorkflowTemplate
      name: triage-indexer
      namespace: ai
      jqPathExpressions:
        - ".spec.templates[].containerSet.archiveLogs"
