apiVersion: v1
kind: Service
metadata:
  name: skillshare
  namespace: ai
  labels:
    app.kubernetes.io/name: skillshare
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: skillshare
  ports:
    - name: http
      port: 19420
      targetPort: http
      protocol: TCP
