# apps/ai/slack-qa-bot/manifests/externalsecret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slack-qa-bot
  namespace: ai
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: slack-qa-bot
    creationPolicy: Owner
  data:
    - secretKey: SLACK_BOT_TOKEN
      remoteRef:
        key: Labot
        property: bot-token
    - secretKey: SLACK_APP_TOKEN
      remoteRef:
        key: Labot
        property: app-token
    - secretKey: LITELLM_KEY
      remoteRef:
        key: Labot
        property: litellm-token
