apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: core
  source:
    repoURL: https://github.com/fwfurtado/the-lab-zone.git
    targetRevision: main
    path: apps/core/gateway-api-crds/crd/experimental
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false          # CRDs: nunca prune automático (segurança)
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
