crds:
  enabled: true
  experimental: false

webhook:
  enabled: false

monitoring:
  enabled: false

additionalCmdFlags:
  - --namespace=data

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
