apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: ollama-default-deny-ingress
  namespace: ai
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: ollama
  ingress:
    - {}
