# apps/ai/triage-webhook/app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: triage-webhook
  namespace: argocd
spec:
  project: ai
  source:
    repoURL: https://github.com/fwfurtado/the-lab-zone.git
    targetRevision: main
    path: apps/ai/triage-webhook/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: ai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
