apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policy-reporter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: security
  sources:
    - repoURL: https://kyverno.github.io/policy-reporter
      chart: policy-reporter
      targetRevision: 3.8.1
      helm:
        releaseName: policy-reporter
        valueFiles:
          - $values/apps/security/policy-reporter/values.yaml
    - repoURL: https://github.com/fwfurtado/the-lab-zone.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/fwfurtado/the-lab-zone.git
      targetRevision: main
      path: apps/security/policy-reporter/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: policy-reporter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      # CRDs/PolicyReports podem ser grandes e os CRDs podem chegar junto do app.
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - CreateNamespace=true
