locals {
  authentik_fqdn = "auth.mgmt.the-lab.zone"

  # Compose entregue VERBATIM via base64 (a string base64 não tem ${...}, então
  # passa intacta pela interpolação do TF; o arquivo decodificado preserva o
  # `$${...}` dos healthchecks e os refs de env_file).
  compose_b64 = base64encode(file("${path.module}/files/docker-compose.yml"))

  # Top-level 100% POSIX (pode rodar em dash): grava o script real e executa com
  # `bash` EXPLÍCITO, redirecionando pro log. Bash-ismos só dentro do arquivo.
  # Heredocs 'EOF'/'PROVEOF' quoted = shell não expande; o TF já interpolou os
  # ${...} antes. Shell vars usam $VAR (sem chaves) p/ não colidir com o TF.
  authentik_script = [
    "set -e",
    "cat > /root/provision-authentik.sh <<'PROVEOF'",
    "#!/usr/bin/env bash",
    "set -euo pipefail",
    "trap 'echo \"[authentik-provision] FALHOU -> $BASH_COMMAND (linha $LINENO)\" >&2' ERR",
    "cloud-init status --wait || true",
    "export DEBIAN_FRONTEND=noninteractive",

    "echo '==> [1/6] apt + docker + rclone'",
    "apt-get update -qq",
    "apt-get install -y -qq ca-certificates curl unzip",
    "curl -fsSL https://get.docker.com | sh",
    "systemctl enable --now docker",
    # O instalador do rclone retorna exit 3 quando já está na última versão ->
    # com set -e isso quebraria a RE-provisão. Guard: só instala se faltar.
    "command -v rclone >/dev/null 2>&1 || curl -fsSL https://rclone.org/install.sh | bash",
    "mkdir -p /opt/authentik/pgdata /opt/authentik/redis /opt/authentik/media /opt/authentik/templates /opt/authentik/certs /opt/authentik/backups",

    "echo '==> [2/6] .env (segredos) + compose'",
    "cat > /opt/authentik/.env <<'EOF'",
    "POSTGRES_USER=authentik",
    "POSTGRES_DB=authentik",
    "POSTGRES_PASSWORD=${var.authentik_pg_password}",
    "AUTHENTIK_SECRET_KEY=${var.authentik_secret_key}",
    "AUTHENTIK_POSTGRESQL__HOST=postgresql",
    "AUTHENTIK_POSTGRESQL__USER=authentik",
    "AUTHENTIK_POSTGRESQL__NAME=authentik",
    "AUTHENTIK_POSTGRESQL__PASSWORD=${var.authentik_pg_password}",
    "AUTHENTIK_REDIS__HOST=redis",
    # 2026.5 mudou o listen default p/ [::]; fixamos 0.0.0.0 p/ não quebrar o publish IPv4.
    "AUTHENTIK_LISTEN__HTTP=0.0.0.0:9000",
    "AUTHENTIK_LISTEN__HTTPS=0.0.0.0:9443",
    "AUTHENTIK_ERROR_REPORTING__ENABLED=false",
    "AUTHENTIK_DISABLE_UPDATE_CHECK=true",
    "AUTHENTIK_DISABLE_STARTUP_ANALYTICS=true",
    # Bootstrap: provisiona o akadmin + um token de API na 1a subida (handoff p/ SSO).
    "AUTHENTIK_BOOTSTRAP_EMAIL=${var.authentik_admin_email}",
    "AUTHENTIK_BOOTSTRAP_PASSWORD=${var.authentik_admin_password}",
    "AUTHENTIK_BOOTSTRAP_TOKEN=${var.authentik_admin_token}",
    "EOF",
    "chmod 600 /opt/authentik/.env",
    "echo '${local.compose_b64}' | base64 -d > /opt/authentik/docker-compose.yml",

    "echo '==> [3/6] TLS via lego (DNS-01)'",
    "mkdir -p /etc/lego",
    "cat > /etc/lego/cloudflare.env <<'EOF'",
    "CF_DNS_API_TOKEN=${var.cloudflare_dns_api_token}",
    "EOF",
    "chmod 600 /etc/lego/cloudflare.env",
    "if [ ! -f /etc/lego/certificates/${local.authentik_fqdn}.crt ]; then docker run --rm --env-file /etc/lego/cloudflare.env -v /etc/lego:/etc/lego ${var.lego_image} run --accept-tos --email ${var.acme_email} --dns cloudflare --dns.resolvers ${var.acme_propagation_resolver} --domains ${local.authentik_fqdn} --path /etc/lego; fi",
    # Deploy do cert pro dir que o Authentik faz auto-discovery (/certs). Key 0644:
    # o processo do Authentik (uid != root) precisa ler; o host /opt/authentik/certs
    # é root-only, então a exposição fica contida no container.
    "cat > /usr/local/bin/authentik-cert-deploy.sh <<'EOF'",
    "#!/bin/sh",
    "set -e",
    "CRT=$(find /etc/lego -type f -name '${local.authentik_fqdn}.crt' | head -1)",
    "KEY=$(find /etc/lego -type f -name '${local.authentik_fqdn}.key' | head -1)",
    "test -n \"$CRT\" && test -n \"$KEY\"",
    "install -m 0644 \"$CRT\" /opt/authentik/certs/authentik.crt",
    "install -m 0644 \"$KEY\" /opt/authentik/certs/authentik.key",
    "EOF",
    "chmod +x /usr/local/bin/authentik-cert-deploy.sh",
    "/usr/local/bin/authentik-cert-deploy.sh",

    "echo '==> [4/6] backup (pg_dump -> B2) + timer'",
    "cat > /root/.authentik-backup.env <<'EOF'",
    "RCLONE_CONFIG_B2_TYPE=b2",
    "RCLONE_CONFIG_B2_ACCOUNT=${var.b2_backup_key_id}",
    "RCLONE_CONFIG_B2_KEY=${var.b2_backup_key}",
    "RCLONE_CONFIG_B2_HARD_DELETE=true",
    "B2_BUCKET=${var.b2_backup_bucket}",
    "KEEP=${var.backup_keep}",
    "EOF",
    "chmod 600 /root/.authentik-backup.env",
    "cat > /usr/local/bin/authentik-backup.sh <<'EOF'",
    "#!/usr/bin/env bash",
    "set -euo pipefail",
    "cd /opt/authentik",
    "ts=$(date -u +%Y%m%d-%H%M%S)",
    "out=/opt/authentik/backups/authentik-$ts.dump",
    # -Fc (custom, comprimido) restaura com pg_restore no MESMO major (PG16).
    "docker compose exec -T postgresql pg_dump -U authentik -Fc authentik > \"$out\"",
    "rclone copy \"$out\" \"b2:$B2_BUCKET/authentik/\"",
    # poda local: mantém os KEEP mais novos",
    "ls -1t /opt/authentik/backups/authentik-*.dump | tail -n +$((KEEP+1)) | xargs -r rm -f",
    # poda remota: mantém os KEEP mais novos (nomes timestampados ordenam sozinhos)",
    "rclone lsf \"b2:$B2_BUCKET/authentik/\" | sort -r | tail -n +$((KEEP+1)) | while read -r f; do rclone deletefile \"b2:$B2_BUCKET/authentik/$f\"; done",
    "echo \"backup ok: $out\"",
    "EOF",
    "chmod +x /usr/local/bin/authentik-backup.sh",
    "cat > /etc/systemd/system/authentik-backup.service <<'EOF'",
    "[Unit]",
    "Description=Backup do Authentik (pg_dump -> B2)",
    "After=docker.service",
    "Requires=docker.service",
    "[Service]",
    "Type=oneshot",
    "EnvironmentFile=/root/.authentik-backup.env",
    "ExecStart=/usr/local/bin/authentik-backup.sh",
    "EOF",
    "cat > /etc/systemd/system/authentik-backup.timer <<'EOF'",
    "[Unit]",
    "Description=Backup diario do Authentik",
    "[Timer]",
    "OnCalendar=daily",
    "RandomizedDelaySec=1800",
    "Persistent=true",
    "[Install]",
    "WantedBy=timers.target",
    "EOF",

    "echo '==> [5/6] lego-renew timer'",
    "cat > /etc/systemd/system/lego-renew.service <<'EOF'",
    "[Unit]",
    "Description=Renova TLS via lego (DNS-01) e recarrega o Authentik server",
    "After=docker.service",
    "Requires=docker.service",
    "[Service]",
    "Type=oneshot",
    "ExecStart=/usr/bin/docker run --rm --env-file /etc/lego/cloudflare.env -v /etc/lego:/etc/lego ${var.lego_image} renew --days 30 --accept-tos --email ${var.acme_email} --dns cloudflare --dns.resolvers ${var.acme_propagation_resolver} --domains ${local.authentik_fqdn} --path /etc/lego",
    "ExecStartPost=/usr/local/bin/authentik-cert-deploy.sh",
    "ExecStartPost=/bin/sh -c 'cd /opt/authentik && docker compose restart server'",
    "EOF",
    "cat > /etc/systemd/system/lego-renew.timer <<'EOF'",
    "[Unit]",
    "Description=Checagem diaria de renovacao do cert (lego)",
    "[Timer]",
    "OnCalendar=daily",
    "RandomizedDelaySec=3600",
    "Persistent=true",
    "[Install]",
    "WantedBy=timers.target",
    "EOF",

    "echo '==> [6/6] subir o stack + timers'",
    "cd /opt/authentik && docker compose up -d",
    "systemctl daemon-reload",
    "systemctl enable --now lego-renew.timer authentik-backup.timer",
    "echo '==> authentik provisionado'",
    "PROVEOF",
    "chmod 600 /root/provision-authentik.sh",
    "bash /root/provision-authentik.sh > /var/log/authentik-provision.log 2>&1",
  ]
}
