apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qdrant-apikey-ai
  namespace: ai
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: qdrant-apikey-ai
    creationPolicy: Owner
  data:
    - secretKey: apiKey
      remoteRef:
        key: qdrant
        property: apiKey
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
