locals {
  pdns_script = [
    "apt-get update -qq",
    "DEBIAN_FRONTEND=noninteractive apt-get install -y -qq pdns-server pdns-backend-sqlite3 sqlite3 pdns-recursor",
    "systemctl stop pdns pdns-recursor || true",
    "mkdir -p /var/lib/powerdns",
    "[ -f /var/lib/powerdns/pdns.sqlite3 ] || sqlite3 /var/lib/powerdns/pdns.sqlite3 < /usr/share/pdns-backend-sqlite3/schema/schema.sqlite3.sql",
    "chown -R pdns:pdns /var/lib/powerdns",
    # AUTH: só local, na 5300 (libera a :53). API/webserver continuam na 8081:
    "cat > /etc/powerdns/pdns.conf <<'EOF'",
    "launch=gsqlite3",
    "gsqlite3-database=/var/lib/powerdns/pdns.sqlite3",
    "local-address=127.0.0.1:5300",
    "api=yes",
    "api-key=${var.pdns_api_key}",
    "webserver=yes",
    "webserver-address=0.0.0.0",
    "webserver-port=8081",
    "webserver-allow-from=10.40.0.0/21",
    "EOF",
    "rm -f /etc/powerdns/pdns.d/bind.conf",
    # RECURSOR: face pra LAN na :53, forwarda the-lab.zone pro auth local:
    "rm -f /etc/powerdns/recursor.conf",
    "cat > /etc/powerdns/recursor.yml <<'EOF'",
    "incoming:",
    "  listen:",
    "    - ${var.dns_ip}",
    "  allow_from:",
    "    - 10.40.0.0/21",
    "recursor:",
    "  forward_zones:",
    "    - zone: the-lab.zone",
    "      forwarders:",
    "        - 127.0.0.1:5300",
    "EOF",
    "systemctl restart pdns",
    "systemctl restart pdns-recursor",
    "systemctl enable pdns pdns-recursor",
  ]
}
