clusterName: lab-zone
talosVersion: v1.13.4 # mesma da ISO
kubernetesVersion: v1.33.1
endpoint: https://10.40.6.10:6443 # VIP — explico abaixo

clusterPodNets:
  - 10.245.0.0/16
clusterSvcNets:
  - 10.97.0.0/16

allowSchedulingOnControlPlanes: false

cniConfig:
  name: none # Cilium entra na Fase 2, via bootstrap

controlPlane:
  patches:
    - "@patches/control-planes/bind-address.yaml"
worker:
  patches:
    - "@patches/workers/user-volume-config.yaml"

patches:
  - "@patches/all/registry-mirrors.yaml"
  - "@patches/all/disable-kube-proxy.yaml"
  - "@patches/all/ntp-and-dns.yaml"

nodes:
  - hostname: cp-1
    ipAddress: 10.40.6.11
    controlPlane: true
    talosImageURL: factory.talos.dev/installer/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515
    installDiskSelector:
      size: "<= 70GB" # acha o disco de 60GB da VM
    networkInterfaces:
      - deviceSelector:
          busPath: "0*" # primeira NIC virtio
        addresses: [10.40.6.11/21]
        routes:
          - network: 0.0.0.0/0
            gateway: 10.40.0.1
        vip:
          ip: 10.40.6.10 # VIP compartilhado entre os CPs
  - hostname: cp-2
    ipAddress: 10.40.6.12
    controlPlane: true
    talosImageURL: factory.talos.dev/installer/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515
    installDiskSelector:
      size: "<= 70GB" # acha o disco de 60GB da VM
    networkInterfaces:
      - deviceSelector:
          busPath: "0*" # primeira NIC virtio
        addresses: [10.40.6.12/21]
        routes:
          - network: 0.0.0.0/0
            gateway: 10.40.0.1
        vip:
          ip: 10.40.6.10 # VIP compartilhado entre os CPs
  - hostname: cp-3
    ipAddress: 10.40.6.13
    controlPlane: true
    talosImageURL: factory.talos.dev/installer/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515
    installDiskSelector:
      size: "<= 70GB" # acha o disco de 60GB da VM
    networkInterfaces:
      - deviceSelector:
          busPath: "0*" # primeira NIC virtio
        addresses: [10.40.6.13/21]
        routes:
          - network: 0.0.0.0/0
            gateway: 10.40.0.1
        vip:
          ip: 10.40.6.10 # VIP compartilhado entre os CPs

  - hostname: worker-1
    ipAddress: 10.40.6.21
    controlPlane: false
    talosImageURL: factory.talos.dev/installer/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515
    installDiskSelector:
      size: ">= 90GB"
    patches:
      - "@patches/workers/user-volume-config-ssd.yaml"
    networkInterfaces:
      - deviceSelector:
          busPath: "0*"
        addresses:
          - 10.40.6.21/21
        routes:
          - network: 0.0.0.0/0
            gateway: 10.40.0.1

  - hostname: worker-2
    ipAddress: 10.40.6.22
    controlPlane: false
    talosImageURL: factory.talos.dev/installer/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515
    installDiskSelector:
      size: ">= 90GB"
    patches:
      - "@patches/workers/user-volume-config-ssd.yaml"
    networkInterfaces:
      - deviceSelector:
          busPath: "0*"
        addresses:
          - 10.40.6.22/21
        routes:
          - network: 0.0.0.0/0
            gateway: 10.40.0.1

  - hostname: worker-3-gpu
    ipAddress: 10.40.6.23
    controlPlane: false
    talosImageURL: factory.talos.dev/installer/6698d6f136c5bb37ca8bb8482c9084305084da0a5ead1f4dcae760796f8ab3a2
    installDiskSelector:
      size: "<= 600GB" # pega o WD Blue 500GB; exclui o WD Black 2TB
    nodeLabels:
      nvidia.com/gpu.present: "true"
    patches:
      - |-
        machine:
          kubelet:
            extraConfig:
              registerWithTaints:
                - key: "nvidia.com/gpu"
                  value: "present"
                  effect: "NoSchedule"
    kernelModules:
      - name: nvidia
      - name: nvidia_uvm
      - name: nvidia_drm
      - name: nvidia_modeset
    machineFiles:
      - op: create
        path: /var/cri/conf.d/20-nvidia.part
        permissions: 0o644
        content: |
          [plugins]
            [plugins."io.containerd.cri.v1.runtime"]
              [plugins."io.containerd.cri.v1.runtime".containerd]
                [plugins."io.containerd.cri.v1.runtime".containerd.runtimes]
                  [plugins."io.containerd.cri.v1.runtime".containerd.runtimes.nvidia]
                    runtime_type = "io.containerd.runc.v2"
                    [plugins."io.containerd.cri.v1.runtime".containerd.runtimes.nvidia.options]
                      BinaryName = "/usr/bin/nvidia-container-runtime"
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:fc:e7:68:77:e0"
        addresses:
          - 10.40.6.23/21
        routes:
          - network: 0.0.0.0/0
            gateway: 10.40.0.1
